SELECT * FROM dairy.images;
INSERT INTO dairy.images (parent_id, parent_type, image_url) VALUES
(6, 'PRODUCT', 'https://firebasestorage.googleapis.com/v0/b/dairy-7d363.appspot.com/o/enfamil-a-so-4-1700g-2flex.png?alt=media'),
(6, 'PRODUCT', 'https://firebasestorage.googleapis.com/v0/b/dairy-7d363.appspot.com/o/enfamil-a-so-4-1700g-2flex%20(1).png?alt=media'),
(6, 'PRODUCT', 'https://firebasestorage.googleapis.com/v0/b/dairy-7d363.appspot.com/o/enfamil-a-so-4-1700g-2flex%20(2).png?alt=media'),
(6, 'PRODUCT', 'https://firebasestorage.googleapis.com/v0/b/dairy-7d363.appspot.com/o/enfamil-a-so-4-1700g-2flex%20(3).png?alt=media'),
(5, 'PRODUCT', 'https://firebasestorage.googleapis.com/v0/b/dairy-7d363.appspot.com/o/enfamil-enspire-infant-formula-0-12-thang-tuoi-850g-hop-giay.png?alt=media'),
(5, 'PRODUCT', 'https://firebasestorage.googleapis.com/v0/b/dairy-7d363.appspot.com/o/enfamil-enspire-infant-formula-0-12-thang-tuoi-850g-hop-giay%20(1).png?alt=media'),
(5, 'PRODUCT', 'https://firebasestorage.googleapis.com/v0/b/dairy-7d363.appspot.com/o/enfamil-enspire-infant-formula-0-12-thang-tuoi-850g-hop-giay%20(2).png?alt=media'),
(5, 'PRODUCT', 'https://firebasestorage.googleapis.com/v0/b/dairy-7d363.appspot.com/o/enfamil-enspire-infant-formula-0-12-thang-tuoi-850g-hop-giay.jpg?alt=media'),
(4, 'PRODUCT', 'https://firebasestorage.googleapis.com/v0/b/dairy-7d363.appspot.com/o/abbott-pediasure-huong-vani-1-10-tuoi-1-6kg.png?alt=media'),
(4, 'PRODUCT', 'https://firebasestorage.googleapis.com/v0/b/dairy-7d363.appspot.com/o/abbott-pediasure-huong-vani-1-10-tuoi-1-6kg.jpg?alt=media'),
(4, 'PRODUCT', 'https://firebasestorage.googleapis.com/v0/b/dairy-7d363.appspot.com/o/abbott-pediasure-huong-vani-1-10-tuoi-1-6kg%20(1).jpg?alt=media'),
(4, 'PRODUCT', 'https://firebasestorage.googleapis.com/v0/b/dairy-7d363.appspot.com/o/abbott-pediasure-huong-vani-1-10-tuoi-1-6kg%20(2).jpg?alt=media'),
(3, 'PRODUCT', 'https://firebasestorage.googleapis.com/v0/b/dairy-7d363.appspot.com/o/nutramigen-a-lgg-400g.png?alt=media'),
(3, 'PRODUCT', 'https://firebasestorage.googleapis.com/v0/b/dairy-7d363.appspot.com/o/nutramigen-a-lgg-400g%20(1).png?alt=media'),
(3, 'PRODUCT', 'https://firebasestorage.googleapis.com/v0/b/dairy-7d363.appspot.com/o/nutramigen-a-lgg-400g%20(2).png?alt=media'),
(3, 'PRODUCT', 'https://firebasestorage.googleapis.com/v0/b/dairy-7d363.appspot.com/o/nutramigen-a-lgg-400g%20(3).png?alt=media'),
(3, 'PRODUCT', 'https://firebasestorage.googleapis.com/v0/b/dairy-7d363.appspot.com/o/nutramigen-a-lgg-400g%20(4).png?alt=media'),
(3, 'PRODUCT', 'https://firebasestorage.googleapis.com/v0/b/dairy-7d363.appspot.com/o/nutramigen-a-lgg-400g%20(5).png?alt=media'),
(2, 'PRODUCT', 'https://firebasestorage.googleapis.com/v0/b/dairy-7d363.appspot.com/o/sua-abbott-grow-4-1-7kg-tren-2-tuoi-huong-vani.jpg?alt=media'),
(1, 'PRODUCT', 'https://firebasestorage.googleapis.com/v0/b/dairy-7d363.appspot.com/o/sua-similac-5g-so-2-900g-6-12-thang.png?alt=media'),
(1, 'PRODUCT', 'https://firebasestorage.googleapis.com/v0/b/dairy-7d363.appspot.com/o/sua-similac-5g-so-2-900g-6-12-thang%20(1).png?alt=media'),
(1, 'PRODUCT', 'https://firebasestorage.googleapis.com/v0/b/dairy-7d363.appspot.com/o/sua-similac-5g-so-2-900g-6-12-thang%20(2).png?alt=media'),
(1, 'PRODUCT', 'https://firebasestorage.googleapis.com/v0/b/dairy-7d363.appspot.com/o/sua-similac-5g-so-2-900g-6-12-thang.jpg?alt=media'),
(1, 'PRODUCT', 'https://firebasestorage.googleapis.com/v0/b/dairy-7d363.appspot.com/o/sua-similac-5g-so-2-900g-6-12-thang%20(1).jpg?alt=media'),
(1, 'PRODUCT', 'https://firebasestorage.googleapis.com/v0/b/dairy-7d363.appspot.com/o/sua-similac-5g-so-2-900g-6-12-thang%20(2).jpg?alt=media');


INSERT INTO dairy.images (parent_id, parent_type, image_url) VALUES
(7, 'PRODUCT', 'https://firebasestorage.googleapis.com/v0/b/dairy-7d363.appspot.com/o/morinaga-so-3-huong-vani-kodomil-tren-3-tuoi-850g.jpg?alt=media'),
(7, 'PRODUCT', 'https://firebasestorage.googleapis.com/v0/b/dairy-7d363.appspot.com/o/morinaga-so-3-huong-vani-kodomil-tren-3-tuoi-850g%20(1).jpg?alt=media'),
(7, 'PRODUCT', 'https://firebasestorage.googleapis.com/v0/b/dairy-7d363.appspot.com/o/morinaga-so-3-huong-vani-kodomil-tren-3-tuoi-850g%20(2).jpg?alt=media'),
(7, 'PRODUCT', 'https://firebasestorage.googleapis.com/v0/b/dairy-7d363.appspot.com/o/morinaga-so-3-huong-vani-kodomil-tren-3-tuoi-850g%20(3).jpg?alt=media'),
(8, 'PRODUCT', 'https://firebasestorage.googleapis.com/v0/b/dairy-7d363.appspot.com/o/sua-bau-morinaga-e-okasan-huong-tra-sua-800g.jpg?alt=media'),
(8, 'PRODUCT', 'https://firebasestorage.googleapis.com/v0/b/dairy-7d363.appspot.com/o/sua-bau-morinaga-e-okasan-huong-tra-sua-800g%20(1).jpg?alt=media'),
(8, 'PRODUCT', 'https://firebasestorage.googleapis.com/v0/b/dairy-7d363.appspot.com/o/sua-bau-morinaga-e-okasan-huong-tra-sua-800g%20(2).jpg?alt=media'),
(8, 'PRODUCT', 'https://firebasestorage.googleapis.com/v0/b/dairy-7d363.appspot.com/o/sua-bau-morinaga-e-okasan-huong-tra-sua-800g%20(3).jpg?alt=media'),
(9, 'PRODUCT', 'https://firebasestorage.googleapis.com/v0/b/dairy-7d363.appspot.com/o/meiji-infant-formula-800g-0-12-thang.jpg?alt=media'),
(9, 'PRODUCT', 'https://firebasestorage.googleapis.com/v0/b/dairy-7d363.appspot.com/o/meiji-infant-formula-800g-0-12-thang%20(1).jpg?alt=media'),
(9, 'PRODUCT', 'https://firebasestorage.googleapis.com/v0/b/dairy-7d363.appspot.com/o/meiji-infant-formula-800g-0-12-thang%20(2).jpg?alt=media'),
(9, 'PRODUCT', 'https://firebasestorage.googleapis.com/v0/b/dairy-7d363.appspot.com/o/meiji-infant-formula-800g-0-12-thang%20(3).jpg?alt=media'),
(10, 'PRODUCT', 'https://firebasestorage.googleapis.com/v0/b/dairy-7d363.appspot.com/o/morinaga-so-1-hagukumi-0-6-thang-850g.jpg?alt=media'),
(10, 'PRODUCT', 'https://firebasestorage.googleapis.com/v0/b/dairy-7d363.appspot.com/o/morinaga-so-1-hagukumi-0-6-thang-850g%20(1).jpg?alt=media'),
(10, 'PRODUCT', 'https://firebasestorage.googleapis.com/v0/b/dairy-7d363.appspot.com/o/morinaga-so-1-hagukumi-0-6-thang-850g%20(2).jpg?alt=media'),
(10, 'PRODUCT', 'https://firebasestorage.googleapis.com/v0/b/dairy-7d363.appspot.com/o/morinaga-so-1-hagukumi-0-6-thang-850g%20(3).jpg?alt=media'),
(11, 'PRODUCT', 'https://firebasestorage.googleapis.com/v0/b/dairy-7d363.appspot.com/o/wakodo-lebens-mom-850g.png?alt=media'),
(11, 'PRODUCT', 'https://firebasestorage.googleapis.com/v0/b/dairy-7d363.appspot.com/o/wakodo-lebens-mom-850g%20(1).png?alt=media'),
(11, 'PRODUCT', 'https://firebasestorage.googleapis.com/v0/b/dairy-7d363.appspot.com/o/wakodo-lebens-mom-850g%20(2).png?alt=media'),
(11, 'PRODUCT', 'https://firebasestorage.googleapis.com/v0/b/dairy-7d363.appspot.com/o/wakodo-lebens-mom-850g%20(3).png?alt=media');